# Generated by Django 6.0.4 on 2026-06-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_configuracionrestaurante_restaurante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('esta_abierta', models.BooleanField(default=True)),
                ('monto_inicial', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('nombre_cajero', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante')),
            ],
        ),
    ]
