# Generated by Django 6.0.4 on 2026-06-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('core', '0004_remove_configuracionrestaurante_restaurante_and_more'),
        ('pedidos', '0004_remove_pedido_sesion_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('nombre_cajero', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante')),
            ],
        ),
        migrations.DeleteModel(
            name='SesionCaja',
        ),
    ]
