# Generated by Django 6.0.4 on 2026-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_caja_delete_sesioncaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='esta_abierta',
            field=models.BooleanField(default=False),
        ),
    ]
