# Generated by Django 6.0.4 on 2026-06-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_caja_esta_abierta'),
        ('core', '0004_remove_configuracionrestaurante_restaurante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante'),
        ),
    ]
