# Generated by Django 6.0.4 on 2026-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_caja_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
