# Generated by Django 6.0.4 on 2026-08-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_caja_monto_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='diferencia_caja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='efectivo_contado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
