# Generated by Django 6.0.4 on 2026-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='cerrado', max_length=10)),
                ('tipo_local', models.CharField(choices=[('restaurante', 'Restaurante'), ('local', 'Local')], default='restaurante', max_length=20)),
                ('propina_activa', models.BooleanField(default=False)),
                ('porcentaje_propina', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
            ],
        ),
    ]
