# Generated by Django 6.0.4 on 2026-06-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_caja', models.CharField(choices=[('central', 'Caja central'), ('garzon', 'Garzón cobra'), ('mixto', 'Mixto')], default='central', max_length=20)),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='core.restaurante')),
            ],
        ),
    ]
