# Generated by Django 6.0.4 on 2026-06-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='tipo_local',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('local', 'Local')], default='restaurante', max_length=20),
        ),
    ]
