# Generated by Django 6.0.4 on 2026-06-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionrestaurante',
            name='restaurante',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='ConfiguracionRestaurante',
        ),
    ]
