# Generated by Django 6.0.4 on 2026-06-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurante_tipo_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='porcentaje_propina',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='propina_activa',
            field=models.BooleanField(default=False),
        ),
    ]
