# Generated by Django 6.0.4 on 2026-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_configuracionrestaurante_restaurante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='acepta_pago_retiro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='acepta_pago_transferencia',
            field=models.BooleanField(default=False),
        ),
    ]
