# Generated by Django 6.0.4 on 2026-08-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurante_acepta_pago_retiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='acepta_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='acepta_retiro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='banco_transferencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='correo_transferencia',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='numero_cuenta_transferencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='pedidos_online_activos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='rut_transferencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='tipo_cuenta_transferencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='titular_transferencia',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
