# Generated by Django 6.0.4 on 2026-08-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_restaurante_acepta_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='acepta_retiro',
            new_name='acepta_pago_local',
        ),
    ]
