# Generated by Django 6.0.4 on 2026-08-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_acepta_retiro_restaurante_acepta_pago_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='acepta_pago_retiro',
            new_name='acepta_retiro',
        ),
    ]
