# Generated by Django 6.0.4 on 2026-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_acepta_pago_retiro_restaurante_acepta_retiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='acepta_pago_local',
            new_name='acepta_pago_delivery',
        ),
        migrations.RenameField(
            model_name='restaurante',
            old_name='acepta_pago_transferencia',
            new_name='acepta_transferencia_delivery',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='acepta_pago_retiro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='acepta_transferencia_retiro',
            field=models.BooleanField(default=False),
        ),
    ]
