# Generated by Django 6.0.4 on 2026-08-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_acepta_pago_local_restaurante_acepta_pago_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='acepta_pago_delivery',
            new_name='acepta_pago_local',
        ),
        migrations.RenameField(
            model_name='restaurante',
            old_name='acepta_transferencia_delivery',
            new_name='acepta_pago_transferencia',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='acepta_pago_retiro',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='acepta_transferencia_retiro',
        ),
    ]
