# Generated by Django 6.0.4 on 2026-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_acepta_pago_local_restaurante_acepta_efectivo_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/logos/'),
        ),
    ]
