# Generated by Django 6.0.4 on 2026-08-20 16:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_restaurante_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ruta_logo_restaurante),
        ),
    ]
