"""
Django settings for nexagest project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url


# =========================================================
# BASE
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# AUTENTICACIÓN
# =========================================================

LOGIN_REDIRECT_URL = "/despacho/"
LOGOUT_REDIRECT_URL = "/login/"


# =========================================================
# SEGURIDAD
# =========================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-$jvl79bbx*^67o*m*qilpa^**v!!#br9zwr7^b1wn(cx*95$qi"
)

DEBUG = os.environ.get(
    "DEBUG",
    "True"
) == "True"


# =========================================================
# HOSTS
# =========================================================

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "*"
).split(",")


CSRF_TRUSTED_ORIGINS = [
    f"https://{host}"
    for host in ALLOWED_HOSTS
    if host and host != "*"
]


SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https"
)


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "usuarios",
    "mesas",
    "carta",
    "pedidos",
    "core",
    "administracion",

    # django-storages
    "storages",
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================================================
# URLS
# =========================================================

ROOT_URLCONF = "nexagest.urls"


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = "nexagest.wsgi.application"


# =========================================================
# DATABASE
# =========================================================

if os.environ.get("DATABASE_URL"):

    DATABASES = {

        "default": dj_database_url.parse(
            os.environ.get("DATABASE_URL"),
            conn_max_age=600,
        )

    }

else:

    DATABASES = {

        "default": {

            "ENGINE": "django.db.backends.sqlite3",

            "NAME": BASE_DIR / "db.sqlite3",

        }

    }


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Santiago"

USE_I18N = True

USE_TZ = False


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"


# =========================================================
# STORAGE
# =========================================================

# False = desarrollo local
# True = Railway + Bucket

USE_S3 = os.environ.get(
    "USE_S3",
    "False"
) == "True"


if USE_S3:

    # =====================================================
    # RAILWAY → BUCKET S3
    # =====================================================

    STORAGES = {

        "default": {

            "BACKEND":
            "storages.backends.s3.S3Storage",

        },

        "staticfiles": {

            "BACKEND":
            "whitenoise.storage.CompressedManifestStaticFilesStorage",

        },

    }


    # =====================================================
    # CREDENCIALES DEL BUCKET
    # =====================================================

    AWS_ACCESS_KEY_ID = os.environ.get(
        "AWS_ACCESS_KEY_ID"
    )

    AWS_SECRET_ACCESS_KEY = os.environ.get(
        "AWS_SECRET_ACCESS_KEY"
    )

    AWS_STORAGE_BUCKET_NAME = os.environ.get(
        "AWS_S3_BUCKET_NAME"
    )

    AWS_S3_ENDPOINT_URL = os.environ.get(
        "AWS_ENDPOINT_URL"
    )

    AWS_S3_REGION_NAME = os.environ.get(
        "AWS_DEFAULT_REGION"
    )


    # =====================================================
    # CONFIGURACIÓN S3
    # =====================================================

    AWS_S3_FILE_OVERWRITE = False

    AWS_DEFAULT_ACL = None

    AWS_QUERYSTRING_AUTH = True


else:

    # =====================================================
    # LOCAL → DISCO DEL PC
    # =====================================================

    STORAGES = {

        "default": {

            "BACKEND":
            "django.core.files.storage.FileSystemStorage",

        },

        "staticfiles": {

            "BACKEND":
            "whitenoise.storage.CompressedManifestStaticFilesStorage",

        },

    }


    # =====================================================
    # MEDIA LOCAL
    # =====================================================

    MEDIA_URL = "/media/"

    MEDIA_ROOT = BASE_DIR / "media"


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"