# Generated by Django 6.0.4 on 2026-06-17 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carta', '0001_initial'),
        ('core', '0001_initial'),
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Cocina'), ('listo', 'Para Entregar'), ('entregado', 'Servido'), ('cancelado', 'Cancelado'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('enviado_a_cocina', models.DateTimeField(blank=True, null=True)),
                ('total_envios', models.PositiveIntegerField(default=0)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('propina_aplicada', models.BooleanField(default=False)),
                ('monto_propina', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('garzon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.mesa')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('enviado_a_cocina', models.BooleanField(default=False)),
                ('numero_envio', models.PositiveIntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carta.producto')),
            ],
        ),
    ]
