# Generated by Django 6.0.4 on 2026-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='esta_pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Cocina'), ('listo', 'Para Entregar'), ('entregado', 'Servido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
