# Generated by Django 6.0.4 on 2026-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Cocina'), ('listo', 'Para Entregar'), ('entregado', 'Servido'), ('cancelado', 'Cancelado'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
