# Generated by Django 6.0.4 on 2026-06-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_sesion_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='sesion_caja',
        ),
    ]
