# Generated by Django 6.0.4 on 2026-05-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='enviado_a_cocina',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
