# Generated by Django 6.0.4 on 2026-06-24 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_caja_esta_abierta'),
        ('pedidos', '0004_remove_pedido_sesion_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sesion_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.caja'),
        ),
    ]
