# Generated by Django 6.0.4 on 2026-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_sesion_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=20),
        ),
    ]
