# Generated by Django 6.0.4 on 2026-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_enviado_a_cocina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='enviado_a_cocina',
            field=models.BooleanField(default=False),
        ),
    ]
