# Generated by Django 6.0.4 on 2026-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedidoitem_enviado_a_cocina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_envios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='numero_envio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
