# Generated by Django 6.0.4 on 2026-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Cocina'), ('listo', 'Para Entregar'), ('aceptado', 'Aceptado'), ('entregado', 'Servido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
