# Generated by Django 6.0.4 on 2026-08-17 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_estado_pago_pedido_token_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token_seguimiento',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
