# Generated by Django 6.0.4 on 2026-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
