# Generated by Django 6.0.4 on 2026-08-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_pedido_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Cocina'), ('listo', 'Para Entregar'), ('aceptado', 'Aceptado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('en_camino', 'En Camino')], default='pendiente', max_length=20),
        ),
    ]
