# Generated by Django 6.0.4 on 2026-09-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='requiere_cocina',
            field=models.BooleanField(default=True),
        ),
    ]
