# Generated by Django 6.0.4 on 2026-09-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedidoitem_requiere_cocina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='requiere_cocina',
        ),
    ]
