# Generated by Django 6.0.4 on 2026-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('garzon', 'Garzón'), ('cocinero', 'Cocinero'), ('administrador', 'Administrador'), ('encargado', 'Encargado')], max_length=20),
        ),
    ]
