# Generated by Django 6.0.4 on 2026-06-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
