# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('garzon', 'GarzÃ³n'), ('cocinero', 'Cocinero'), ('operador', 'Operador'), ('administrador', 'Administrador'), ('encargado', 'Encargado')], max_length=20),
        ),
    ]
