# Generated by Django 6.0.4 on 2026-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('garzon', 'Garzón'), ('cocinero', 'Cocinero'), ('operador', 'Operador'), ('administrador', 'Administrador'), ('encargado', 'Encargado')], max_length=20),
        ),
    ]
