from django.urls import path
from . import views

urlpatterns = [
    path('', views.menu_admin, name='menu_admin'),
    
    path('reportes/', views.dashboard, name='dashboard'),
    path('toggle-local/', views.toggle_estado_local, name='url_cambiar_estado'),
    path('productos/', views.lista_productos, name='lista_productos'),
    path('administracion/productos/crear/', views.crear_producto, name='crear_producto'),
    path('administracion/productos/editar/<int:producto_id>/', views.editar_producto, name='editar_producto'),
    path('administracion/productos/eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('configuracion-restaurante/', views.configuracion_restaurante, name='configuracion-restaurante'),
    path('administracion/caja/', views.caja, name='caja'),
    path('administracion/caja/abrir/', views.abrir_caja, name='abrir_caja'),
    path('administracion/caja/cerrar/', views.cerrar_caja, name='cerrar_caja'),
    path('administracion/caja/historial/', views.historial_cajas, name='historial_cajas'),
    path('administracion/caja/historial/<int:caja_id>/', views.detalle_caja, name='detalle_historial_caja'),
    path('administracion/gestion-personal/', views.gestion_personal, name='gestion_personal'),
    path('administracion/gestion-personal/garzones/', views.gestionar_garzones, name='gestionar_garzones'),
    path('administracion/gestion-personal/cocineros/', views.gestionar_cocineros, name='gestionar_cocineros'),
    path('administracion/gestion-personal/encargados/', views.gestionar_encargados, name='gestionar_encargados'),
    path('administracion/gestion-personal/operadores/', views.gestionar_operadores, name='gestionar_operadores'),
    path('administracion/gestion-personal/garzones/agregar/', views.agregar_garzon, name='agregar_garzon'),
    path('administracion/gestion-personal/garzones/desactivar/<int:garzon_id>/',views.desactivar_garzon,name='desactivar_garzon'),
    path('administracion/gestion-personal/garzones/activar/<int:garzon_id>/',views.activar_garzon,name='activar_garzon'),
    path('administracion/gestion-personal/cocineros/agregar/', views.agregar_cocinero, name='agregar_cocinero'),
    path('administracion/gestion-personal/cocineros/desactivar/<int:cocinero_id>/',views.desactivar_cocinero,name='desactivar_cocinero'),
    path('administracion/gestion-personal/cocineros/activar/<int:cocinero_id>/',views.activar_cocinero,name='activar_cocinero'),
    path('administracion/gestion-personal/encargados/agregar/', views.agregar_encargado, name='agregar_encargado'),
    path('administracion/gestion-personal/encargados/desactivar/<int:encargado_id>/', views.desactivar_encargado, name='desactivar_encargado'),
    path('administracion/gestion-personal/encargados/activar/<int:encargado_id>/', views.activar_encargado, name='activar_encargado'),
    path('administracion/gestion-personal/operadores/agregar/', views.agregar_operador, name='agregar_operador'),
    path('administracion/gestion-personal/operadores/desactivar/<int:operador_id>/', views.desactivar_operador, name='desactivar_operador'),
    path('administracion/gestion-personal/operadores/activar/<int:operador_id>/', views.activar_operador, name='activar_operador'),
    path('administracion/productos/crear-categoria/', views.crear_categoria, name='crear_categoria'),
    path('administracion/gestion-personal/garzones/contraseña/<int:garzon_id>/', views.reset_password_garzon, name='reset_password_garzon'),
    path('administracion/gestion-personal/cocineros/contraseña/<int:cocinero_id>/', views.reset_password_cocinero, name='reset_password_cocinero'),
    path('administracion/gestion-personal/encargados/contraseña/<int:encargado_id>/', views.reset_password_encargado, name='reset_password_encargado'),
    path('administracion/gestion-personal/operadores/contraseña/<int:operador_id>/', views.reset_password_operador, name='reset_password_operador'),
    path("toggle-estado-local/",views.toggle_estado_local,name="toggle_estado_local"),
]
