# Generated by Django 6.0.4 on 2026-06-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
        ('core', '0003_restaurante_tipo_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.restaurante'),
        ),
    ]
