# Generated by Django 6.0.4 on 2026-08-20 12:37

import carta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=carta.models.ruta_imagen_producto),
        ),
    ]
