# Generated by Django 6.0.4 on 2026-09-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='requiere_cocina',
            field=models.BooleanField(default=True),
        ),
    ]
