# Generated by Django 6.0.4 on 2026-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
